#!/bin/bash
# /etc/init.d/defi_start

### BEGIN INIT INFO
# Provides:          defiscript
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used for defi alarm calling
### END INIT INFO


case "$1" in 
    start)
        echo "Starting defiscript"
        /opt/lemt/defi/defiscript.py &
        ;;
    stop)
        echo "Stopping defiscript"
        kill $(ps aux | grep '[p]ython /opt/lemt/defi/defiscript.py' | awk '{print $2}')
        ;;
    *)
        echo "Usage: /etc/init.d/defiscript start|stop"
        exit 1
        ;;
esac

exit 0
